version: "2"

services:

  proxy:
    image: silvius1/resume-proxy
    mem_limit: 256m
    mem_reservation: 128m
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    networks:
      - subnet
    depends_on:
      - frontend

  frontend:
    image: silvius1/resume-frontend
    mem_limit: 256m
    mem_reservation: 128m
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - subnet

networks:
  subnet:
