# Profile section
profile:
  first_name: Silviu
  last_name: Moisoiu
  picture: static/img/me_groovy.gif  # Local picture
  contact:
    address_one: Bucharest, Romania
    address_two:
    phone: +40 742 998 711
  email: unisilvium@gmail.com
  description: >
     I enjoy working on creative projects and like to
     tackle problems with curiosity and a pragmatic
     mind. Reasonable and balanced I aim to take
     responsibility of things I know I can deliver on. With people i tend to be honest, fair and perseverant.
  interest:
    - Linux
    - DevOps
    - Music
    - Audio Gear
    - Reading
    - Podcasts
    - Nature
    - Art
    - Automation
    - Fishing


# Social section
social:
  github: https://github.com/acupofh2o
  linkedin: https://www.linkedin.com/in/silviu-moisoiu/
  facebook: https://www.facebook.com/silviu.moisoiu1


# Experience section
experience:
  item0:
    position: Linux System & Server Admin
    company: Desilva Intermed
    industry: Real-Estate
    from: May 2018
    to: May 2020
    description:
      - Responsible with provisioning, configuration and management of new/existing servers.
      - Worked on containerization of our micro-services using docker and docker-compose.
      - Implemented orchestration with Kubernetes. Developed unit tests for our authentication service.
      - Developed our email flow and triggers for the authentication service using AWS Lambda.

  item1:
    position: Linux Specialist
    company: Undatech
    industry: 3D Printing & Manufacturing
    from: June 2017
    to: October 2017
    description:
      - Responsible with provisioning, configuration and management of new/existing servers.
      - Got familiarized with the 3D printing workflow.
      - Built python automation scripts for various internal processes.
      - Provisioned and tested different kernel configurations to be used on chips inside 3D printing machines.
  item2:
    position: Project Manager
    company: Indrasoft
    industry: Software Services
    from: June 2016
    to: February 2017
    description:
      - Introduced and planned the development of new features.
      - Marketing, promotion and acquisition of new clients and partners.
      - Maintained relationships with existing investors.
      - Grew our user-base from 0 to ~800 total users in about 4 months.
  item3:
    position: Internship
    company: UPC
    industry: Telecommunications
    from: June 2015
    to: September 2015
    description:
      - Responsible with monitoring of the national coaxial and optic fibre network.
      - Categorized and organized incident responses.
      - Assignment of various incidents to local teams.



# Education section
education:
  item1:
    institution: University Politehnica, Bucharest, Romania
    program: Master of Multimedia technologies for the production of audiovisual content and communications
    from: October 2020
    to: Present
  item2:
    institution: University Politehnica, Bucharest, Romania
    program: Bachelor of Electronics, Telecommunications and Information Technology
    description: Major in Microelectronics, optoelectronics and nanotechnologies
    from: October 2014
    to: Jun 2018
  item3:
    institution: Gheorghe Munteanu Murgoci National College, Braila, Romania
    program: Baccalaureate
    description: Involved in multiple extra-curricular activities like anti-drug awareness programs.
    from: Sep 2010
    to: May 2014


# Community section:
community:
  item0:
    institution: Bucharest.AI
    program: Co-founder
    description: "Launched in 2017, Bucharest.AI is the first community in Romania dedicated to growing the local Artificial Intelligence (AI) ecosystem. Its mission is to tap into local resources in order to position the country as the most advanced AI hub in Central and Eastern Europe."
    from: April 2017
    to: Present
    link: https://bucharest.ai
  item1:
    institution: How to Web Conference
    program: Volunteer
    description: "Helped with organizational logistics and preparation for the 2015 event."
    from: November 2015
    link: https://www.howtoweb.co/
  item2:
    institution: Websummit
    program: Conference
    description: Presented our on demand delivery startup at the event.
    from: November 2016
    link: https://websummit.com/

  item3:
    institution: Innovation Labs
    program: Startup Competition
    description: Held a presentation of my real-estate startup ideea at the event.
    from: March 2016
    link: https://www.innovationlabs.ro/

  item4:
    institution: European Youth Parliament
    program: Camp
    description: Participated in a 1 week camp with the purpose of finding solutions to a set of social & civic problems.
    from: September 2013
    link: https://eyp.org/




# Skills section

skills:
  - Operating systems - Linux(Ubuntu, Debian, CentOS), macOS, Windows
  - Programming Technologie - Python, YAML, Json, Bash, MongoDB, Flask, AWS(Basic)
  - Version Control - Git, Github, Bitbucket
  - Containers - Docker, docker-compose, Kubernetes(basic)
  - Provisioning and automation - Ansible, Jenkins, Jenkins Pipelines
  - Monitoring - Prometheus(basic), Grafana(basic)

extra_skills:
  - UI/UX design using Sketch/Adobe xD
  - Prototyping using Principle
  - Presentation and documents design
  - Basic command of Adobe Creative Suite(Illustrator, Photoshop)
  - Basic command of Google/Microsoft Office Suite




# Projects section
projects:
  item1:
    title: Flask Resume
    subtitle: A resume template built with Flask
    description: A project built on top of a Flask template fork which i developed in an EC2 AWS instance, dockerized it, made it run behind an Nginx reverse-proxy and deployed it to AWS using an Elastic Beanstalk service.
    tags: [Flask, Python, Bootstrap, Docker, EC2, Elastic Beanstalk]
  item2:
    title: Pong Agent
    subtitle: Bachelor's Thesis Project
    description: Built and trained an AI agent that learns to play Pong using based on Reinforcement Learning principles using a Q-Learning algorithm. Dockerized the app for portability purposes.
    tags: [Python, Gym, Keras, Docker, Numpy]
  item3:
    title: IoT Door Lock
    subtitle: Smart door locking system
    description: Built the software interface for smart doorlocking system using Arduino's programming language. The system was comprised of an ESP8266 Wifi module, some servo-motors, a 3D printed case, LEDs, and an RFID sensor. Access was being provided through RFID tags.
    tags: [Arduino, RFID, 3D Printing]
  item4:
    title: IoT Home Monitoring system
    subtitle: Visualising basic stats of a room
    description: Built a home monitoring system comprised of several sensors to gather basic information about humidity, temperature, pressure and sound in a room. The data then gets plotted over time through an API for visualisation purposes.
    tags: [Arduino, Electronic Sensors, API]
  item5:
    title: Audio Pre-Amplifier
    subtitle: Hardware project
    description: Design, implementation and testing of a basic audio pre-amplifier.
    tags: [Audio, Eagle, Soldering, Electronics]
  item6:
    title: RISC Processor
    subtitle: Project highlighting basic RISC funcionality.
    description: Design, implementation and testing of a low level RISC type architecture processor using Verilog.
    tags: [RISC, Verilog, Microprocessors]


# Certifications and certifications section
certifications:
  item1:
    title: Linux System & Server Admin
    issuer: Telecom Academy · Bucharest
    date: July 2018
  item2:
    title: ECCPR Programming Certification
    issuer: Politehnica University · Bucharest
    date: April 2018

courses:
  item1:
    title: Implementing a Full CI/CD Pipeline
    issuer: LinuxAcademy
    date: June - August 2020
  item2:
    title: Linux Foundation Certified SysAdmin (LFCS)
    issuer: LinuxAcademy
    date: June - August 2020
  item3:
    title: Docker Deep Dive & Learn Docker by Doing
    issuer: LinuxAcademy
    date: June - August 2020
  item4:
    title: DevOps Essentials
    issuer: LinuxAcademy
    date: June - August 2020
  item5:
    title: Learn Jenkins by Doing
    issuer: LinuxAcademy
    date: June - August 2020
  item6:
    title: Learn Ansible by Doing
    issuer: LinuxAcademy
    date: June - August 2020
